using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("FluentInjections.Applications")]
[assembly: InternalsVisibleTo("FluentInjections.DependencyInjection")]
[assembly: InternalsVisibleTo("FluentInjections.Collections")]
[assembly: InternalsVisibleTo("FluentInjections.Core")]
[assembly: InternalsVisibleTo("FluentInjections.Events")]
[assembly: InternalsVisibleTo("FluentInjections.Extensions")]
[assembly: InternalsVisibleTo("FluentInjections.Injection")]
[assembly: InternalsVisibleTo("FluentInjections.Utilities.Collections")]
[assembly: InternalsVisibleTo("FluentInjections.Validation")]
[assembly: InternalsVisibleTo("FluentInjections.Tests")]
[assembly: InternalsVisibleTo("FluentInjections.Tests.Infrastructure")]
[assembly: InternalsVisibleTo("FluentInjections.Tests.Units")]
[assembly: InternalsVisibleTo("FluentInjections.Tests.Integration")]
[assembly: InternalsVisibleTo("FluentInjections.Tests.E2E")]
